### ISSUE TITLE
Hash file not saving/updating md5

### ISSUE THREAD

**Issue by mikesilvo164** [mikesilvo164/script.skinshortcuts#5]
Need to encode hash to prevent `Unable to generate hash` errors and it causes a build loop due to the .hash file not updating.

For me it stays at `8c7dd922ad47494fc02c388e12c00eac`

**Comment by mikesilvo164** [comment]
Thinking it is due to the def _save_hash function and the append to filename
`hashlist.list.append( [filename, hasher.hexdigest()] )`

in [datafunctions.py](https://github.com/mikesilvo164/script.skinshortcuts/blob/test_branch/resources/lib/datafunctions.py#L1144)

**Comment by BobCratchett** [comment]
Can't look properly, but I saw your commit earlier and nearly commented. It's because you're saving the hash of the (bytes representation) of the string "file", and not the hash of the file itself.

Code went from

`hasher.update(file.encode("utf8"))`

to

`hasher.update(b"file")`

Once you add the quotation marks around 'file' you're turning it into a string (the b in front tells python how to encode it - in this case as bytes if memory serves). The object that represents the file doesn't have quotation marks.

I'll try to look over where everything at properly mid-week.

Same as https://forum.kodi.tv/showthread.php?tid=178294&pid=2879798#pid2879798

**Comment by mikesilvo164** [comment]
Ok, I'll change that back but it was doing the same thing before making that change.

I looked at the python hashlib documentation and it had this as an example:
`m.update(b"Nobody inspects")`

So I figured I would try it and see if it did anything but it had no effect so I assumed that it was the same as encoding...

Anyway thanks for taking a look, I appreciate your help whenever you can give it 😃

**Comment by BobCratchett** [comment]
I think figuring out this py3 combat hasher stuff is going to take a good old fashioned debug build (with lots of adding debug logging to see exactly what's going on where). In the meantime, if you're wanting to move beyond it, it shouldn't be too much work to disable the file hashing entirely. It's a useful feature and helps deal with a ridiculous number of edge cases, but its primary use case ended up being helping skinners when they were updating their .data.xml files (end users tend not to touch these or the other relevant files) - so probably wouldn't be massively missed until fixed up properly...

**Comment by mikesilvo164** [comment]
@BobCratchett I got the build loop to stop by changing:
`hashlist.list.append( [filename, hasher.hexdigest()] )`
to
`hashlist.list.append([filename.encode("utf8"), hasher.hexdigest()])`

Now I am just getting ` Unable to generate hash for b'C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\16x9\\script-skinshortcuts-includes.xml'` but all the others are gone.

Gonna push that to the python 3 branch cause my test_branch changes broke the menu building so I am going to review them line by line and see where I messed up.

**Comment by mikesilvo164** [comment]
This is probably related. 
The .hash files have different formats.

OLD
```
[['::PROFILELIST::', [[u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\', u'String.IsEqual(System.ProfileName,Master user)', u'Master user'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\', u'String.IsEqual(System.ProfileName,Guest)', u'Guest'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\', u'String.IsEqual(System.ProfileName,Kids)', u'Kids']]], ['::SCRIPTVER::', '1.0.20'], ['::XBMCVER::', '18'], ['::HIDEPVR::', 'false'], ['::SHARED::', 'true'], ['::SKINDIR::', 'skin.aeon.nox.silvo'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\overrides.xml', '9cbd409a00763c0a5921041f145a0de4'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\template.xml', '2cda790c2e846e77cc12df2e61914b2b'], ['::FULLMENU::', 'True'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\mainmenu.DATA.xml', 'fe06d086e4eadffd1f950bcc707d1e84'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\overrides.xml', None], ['C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\skin.aeon.nox.silvo.properties', '2d299e0598d4f1eb5c19db2d3fe6c9b8'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\mainmenu.DATA.xml', '81ef0d1a41f09e2916348add04faf3ec'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\15016.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\music.DATA.xml', 'fc5f61529c0de13b40360874516cd588'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\tvshows.DATA.xml', '567267397238bea92d1590cf23f397f4'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\20342.DATA.xml', '7862c51ea708f958c5ab01193f0bf643'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\videos.DATA.xml', '9de6f1befdc2d0c11709984808b34647'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\videos-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\videos-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\videos-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\videos-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\videos-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\videos-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31957.DATA.xml', '6c7c6b3e04347dad9629ad0e286abdfb'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\13000.DATA.xml', '5ba1683193a5df4f992e7c0a43dba258'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\13000-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\13000-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\13000-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\13000-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\13000-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\13000-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31958.DATA.xml', 'c1c23b946192e7b70f8ec3b948d6c541'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.skinshortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-2.DATA.xml', None], ['::FULLMENU::', 'True'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\mainmenu.DATA.xml', 'ab353d417dade19f5e853f9b2037dfb4'], ['C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\skin.aeon.nox.silvo.properties', 'b25053358e96e2ed44822baf52ca9c66'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\mainmenu.DATA.xml', '81ef0d1a41f09e2916348add04faf3ec'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31957.DATA.xml', '68279839fd58797f6a47adf78d3b5e85'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\music.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music.DATA.xml', '2e9a71a151aa2cc996c24beb4f6628c8'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\tvshows.DATA.xml', '8665a0518e8c209ab84fbaa49e1fa792'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\20342.DATA.xml', '074d70aaed782b5a9b3afef59a9f445a'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\15016.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\137.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31958.DATA.xml', 'febfa78ff3be36181571a55dd7ca1304'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\weather.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Guest\\addon_data\\script.skinshortcuts\\weather-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\weather-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\weather-2.DATA.xml', None], ['::FULLMENU::', 'True'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\mainmenu.DATA.xml', '26254e9ed92fd915154e19e26f294ccc'], ['C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\skin.aeon.nox.silvo.properties', '3ebea811c8dcf0b851bd7b6e7ac0a76e'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\mainmenu.DATA.xml', '81ef0d1a41f09e2916348add04faf3ec'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\music.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music.DATA.xml', '2e9a71a151aa2cc996c24beb4f6628c8'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\music-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\137.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\137-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\137-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\20342.DATA.xml', '05d85f5574d3c180bc00072ed8810c87'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\tvshows.DATA.xml', '8665a0518e8c209ab84fbaa49e1fa792'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\tvshows-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31957.DATA.xml', '68279839fd58797f6a47adf78d3b5e85'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\15016.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31958.DATA.xml', 'febfa78ff3be36181571a55dd7ca1304'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\weather.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\weather-1.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\userdata\\profiles\\Kids\\addon_data\\script.skinshortcuts\\weather-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\shortcuts\\weather-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\script.skinshortcuts\\resources\\shortcuts\\weather-2.DATA.xml', None], [u'C:\\Users\\mikes\\AppData\\Roaming\\Kodi\\addons\\Aeon-Nox-SiLVO\\16x9\\script-skinshortcuts-includes.xml', '730bd10ae229b31e96a6cf3dd0e50626'], ['::SKINVER::', '7.0.4']]
```
NEW
```
[['::PROFILELIST::', [['C:\\Kodi (Python 3)\\portable_data\\userdata\\', 'String.IsEqual(System.ProfileName,Master user)', 'Master user']]], ['::SCRIPTVER::', '1.0.20'], ['::XBMCVER::', '19'], ['::HIDEPVR::', 'false'], ['::SHARED::', 'true'], ['::SKINDIR::', 'skin.aeon.nox.silvo'], [b'C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\overrides.xml', 'e285e553e28f9e61cd85ae9ba096fca5'], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\template.xml', '3c0860bd28be663c8a1cd744e784dc02'], ['::FULLMENU::', 'True'], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\mainmenu.DATA.xml', '75cfa1543e09f974f1f3025dfc623d48'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\overrides.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\mainmenu.DATA.xml', '8e19ac7c50625158fc32fb829273b460'], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\20342.DATA.xml', '6eeaf46b98d5ea899b98b12f7780f2cf'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\20342-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\20342-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\20342-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\20342-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\20342-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\videos.DATA.xml', '1d975c3924bb206bf8ea27255f4339db'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\videos-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\videos-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\videos-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\videos-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\videos-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\videos-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31957.DATA.xml', '0d43c87dba81165c0b6f5dcf55a6d2f6'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31957-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\31957-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31957-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\31957-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\31957-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\15016.DATA.xml', '379c0cb0f0c8c3963235d19fe6e1308b'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\15016-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\15016-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\15016-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\15016-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\15016-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\13000.DATA.xml', 'c71f3dab22b68294168a3461d44dd1ba'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\13000-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\13000-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\13000-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\13000-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\13000-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\13000-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31958.DATA.xml', '16715120710f7a36e36ecf320ab05cf9'], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31958-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\31958-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-1.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\userdata\\addon_data\\script.skinshortcuts\\31958-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\shortcuts\\31958-2.DATA.xml', None], ['C:\\Kodi (Python 3)\\portable_data\\addons\\script.skinshortcuts\\resources\\shortcuts\\31958-2.DATA.xml', None], [b'C:\\Kodi (Python 3)\\portable_data\\addons\\skin.aeon.nox.silvo\\16x9\\script-skinshortcuts-includes.xml', '2c8d71a5a087a60a8cb08e172be35be2'], ['::SKINVER::', '7.9.0']]
```
Looks like unicode to bytes maybe...

**Comment by Ch1llb0** [comment]
Should be fixed here: https://github.com/mikesilvo164/script.skinshortcuts/pull/35

**Comment by anxdpanic** [comment]
Re-open if issue persists with https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.0.alpha2 or higher
